package view;

import java.util.HashMap;
import javax.swing.JLabel;

public class JdlgEscaninho extends javax.swing.JDialog {

    private HashMap<Integer, JLabel> labelMap = new HashMap<Integer, JLabel>();

    public JdlgEscaninho(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        criaVetores();
        clearJLabels();
    }

    private void criaVetores() {
        for (Object o : jpn1.getComponents()) {
            if (o instanceof JLabel) {
                JLabel jlbl = (JLabel) o;
                labelMap.put(Integer.parseInt(jlbl.getName()), jlbl);
            }
        }
    }

    public void clearJLabels() {
        for (int i = 1; i < labelMap.size() + 1; i++) {
            JLabel lbl = labelMap.get(i);
            lbl.setText("");
        }
    }

    public HashMap<Integer, JLabel> getLabelMap() {
        return labelMap;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn1 = new javax.swing.JPanel();
        jlbl1 = new javax.swing.JLabel();
        jlbl2 = new javax.swing.JLabel();
        jlbl3 = new javax.swing.JLabel();
        jlbl4 = new javax.swing.JLabel();
        jlbl5 = new javax.swing.JLabel();
        jlbl6 = new javax.swing.JLabel();
        jlbl7 = new javax.swing.JLabel();
        jlbl8 = new javax.swing.JLabel();
        jlbl9 = new javax.swing.JLabel();
        jlbl10 = new javax.swing.JLabel();
        jlbl11 = new javax.swing.JLabel();
        jlbl12 = new javax.swing.JLabel();
        jlbl13 = new javax.swing.JLabel();
        jlbl14 = new javax.swing.JLabel();
        jlbl15 = new javax.swing.JLabel();
        jlbl16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));

        jlbl1.setBackground(new java.awt.Color(255, 255, 255));
        jlbl1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl1.setText("jLabel1");
        jlbl1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jlbl1.setName("1"); // NOI18N
        jlbl1.setOpaque(true);

        jlbl2.setBackground(new java.awt.Color(255, 255, 255));
        jlbl2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl2.setText("jLabel1");
        jlbl2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jlbl2.setName("2"); // NOI18N
        jlbl2.setOpaque(true);

        jlbl3.setBackground(new java.awt.Color(255, 255, 255));
        jlbl3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl3.setText("jLabel1");
        jlbl3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jlbl3.setName("3"); // NOI18N
        jlbl3.setOpaque(true);

        jlbl4.setBackground(new java.awt.Color(255, 255, 255));
        jlbl4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl4.setText("jLabel1");
        jlbl4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E4", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jlbl4.setName("4"); // NOI18N
        jlbl4.setOpaque(true);

        jlbl5.setBackground(new java.awt.Color(255, 255, 255));
        jlbl5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl5.setText("jLabel1");
        jlbl5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E5", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jlbl5.setName("5"); // NOI18N
        jlbl5.setOpaque(true);

        jlbl6.setBackground(new java.awt.Color(255, 255, 255));
        jlbl6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl6.setText("jLabel1");
        jlbl6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E6", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jlbl6.setName("6"); // NOI18N
        jlbl6.setOpaque(true);

        jlbl7.setBackground(new java.awt.Color(255, 255, 255));
        jlbl7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl7.setText("jLabel1");
        jlbl7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E7", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jlbl7.setName("7"); // NOI18N
        jlbl7.setOpaque(true);

        jlbl8.setBackground(new java.awt.Color(255, 255, 255));
        jlbl8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbl8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl8.setText("jLabel1");
        jlbl8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E8", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jlbl8.setName("8"); // NOI18N
        jlbl8.setOpaque(true);

        jlbl9.setBackground(new java.awt.Color(255, 255, 255));
        jlbl9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbl9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl9.setText("jLabel1");
        jlbl9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E9", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jlbl9.setName("9"); // NOI18N
        jlbl9.setOpaque(true);

        jlbl10.setBackground(new java.awt.Color(255, 255, 255));
        jlbl10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbl10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl10.setText("jLabel1");
        jlbl10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E10", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jlbl10.setName("10"); // NOI18N
        jlbl10.setOpaque(true);

        jlbl11.setBackground(new java.awt.Color(255, 255, 255));
        jlbl11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbl11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl11.setText("jLabel1");
        jlbl11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E11", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jlbl11.setName("11"); // NOI18N
        jlbl11.setOpaque(true);

        jlbl12.setBackground(new java.awt.Color(255, 255, 255));
        jlbl12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbl12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl12.setText("jLabel1");
        jlbl12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E12", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jlbl12.setName("12"); // NOI18N
        jlbl12.setOpaque(true);

        jlbl13.setBackground(new java.awt.Color(255, 255, 255));
        jlbl13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbl13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl13.setText("jLabel1");
        jlbl13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E13", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jlbl13.setName("13"); // NOI18N
        jlbl13.setOpaque(true);

        jlbl14.setBackground(new java.awt.Color(255, 255, 255));
        jlbl14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbl14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl14.setText("jLabel1");
        jlbl14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E14", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jlbl14.setName("14"); // NOI18N
        jlbl14.setOpaque(true);

        jlbl15.setBackground(new java.awt.Color(255, 255, 255));
        jlbl15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbl15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl15.setText("jLabel1");
        jlbl15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E15", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jlbl15.setName("15"); // NOI18N
        jlbl15.setOpaque(true);

        jlbl16.setBackground(new java.awt.Color(255, 255, 255));
        jlbl16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbl16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl16.setText("jLabel1");
        jlbl16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E16", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jlbl16.setName("16"); // NOI18N
        jlbl16.setOpaque(true);

        javax.swing.GroupLayout jpn1Layout = new javax.swing.GroupLayout(jpn1);
        jpn1.setLayout(jpn1Layout);
        jpn1Layout.setHorizontalGroup(
            jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(jlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jlbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jlbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jlbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(jlbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jlbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jlbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jlbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(jlbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jlbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jlbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jlbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(jlbl13, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jlbl14, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jlbl15, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jlbl16, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpn1Layout.setVerticalGroup(
            jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escaninho");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdlgEscaninho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdlgEscaninho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdlgEscaninho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdlgEscaninho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JdlgEscaninho dialog = new JdlgEscaninho(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlbl1;
    private javax.swing.JLabel jlbl10;
    private javax.swing.JLabel jlbl11;
    private javax.swing.JLabel jlbl12;
    private javax.swing.JLabel jlbl13;
    private javax.swing.JLabel jlbl14;
    private javax.swing.JLabel jlbl15;
    private javax.swing.JLabel jlbl16;
    private javax.swing.JLabel jlbl2;
    private javax.swing.JLabel jlbl3;
    private javax.swing.JLabel jlbl4;
    private javax.swing.JLabel jlbl5;
    private javax.swing.JLabel jlbl6;
    private javax.swing.JLabel jlbl7;
    private javax.swing.JLabel jlbl8;
    private javax.swing.JLabel jlbl9;
    private javax.swing.JPanel jpn1;
    // End of variables declaration//GEN-END:variables
}
