package view;

import control.RunCS;
import control.RealceRunCS;
import control.ArquivoCS;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

public class JfrmPrincipal extends javax.swing.JFrame {

    private HashMap<Integer, JTextField> textMap = new HashMap<>();
    private List<JTextField> textFields = new ArrayList<>();
    private RunCS runCS;
    private RealceRunCS rrunCS;
    private ArquivoCS arquivoCS;

    public JfrmPrincipal() {
        initComponents();
        runCS = new RunCS(textMap, this);
        rrunCS = new RealceRunCS(textMap, this);
        criaVetores();
        clearJTextFields(7);
        criaLista();
    }

    private void criaVetores() {
        for (Object o : jpn1.getComponents()) {
            if (o instanceof JTextField) {
                JTextField jtxt = (JTextField) o;
                textMap.put(Integer.parseInt(jtxt.getName()), jtxt);
            }
        }
    }

    private void criaLista() {
        for (Object o : jpn1.getComponents()) {
            if (o instanceof JTextField) {
                JTextField jtxt = (JTextField) o;
                getTextFields().add(jtxt);
                //System.out.println(jtxt.getText());
            }
        }
    }

    private void clearJTextFields(int i) {
        for (; i < textMap.size() + 1; i++) {
            JTextField jtxt = textMap.get(i);
            jtxt.setText("");
        }
    }

    public void blockReformatComponents() {
        for (int i = 1; i < textMap.size() + 1; i++) {
            JTextField jtxt = textMap.get(i);
            jtxt.setText(jtxt.getText().toUpperCase());
            jtxt.setEditable(false);
        }
        txtCartao.setEditable(false);
    }

    public void releaseComponents() {
        for (int i = 1; i < textMap.size() + 1; i++) {
            JTextField jtxt = textMap.get(i);
            jtxt.setEditable(true);
        }
        txtCartao.setEditable(true);
    }

    public List<Integer> getCards() {
        List<Integer> cards = new ArrayList<>();

        for (int i = 0; i < tblCartoes.getRowCount(); i++) {
            Integer card = (int) tblCartoes.getValueAt(i, 0);
            cards.add(card);
        }
        return cards;
    }

    public void listar(List<Integer> cardList) {
        DefaultTableModel modelo = (DefaultTableModel) tblCartoes.getModel();
        modelo.setNumRows(0);

        cardList.forEach((lc) -> {
            modelo.addRow(new Object[]{lc});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtxtE00 = new javax.swing.JTextField();
        jtxtE02 = new javax.swing.JTextField();
        jtxtE03 = new javax.swing.JTextField();
        jtxtE04 = new javax.swing.JTextField();
        jtxtE05 = new javax.swing.JTextField();
        jtxtE06 = new javax.swing.JTextField();
        jtxtE07 = new javax.swing.JTextField();
        jtxtE08 = new javax.swing.JTextField();
        jtxtE09 = new javax.swing.JTextField();
        jtxtE10 = new javax.swing.JTextField();
        jtxtE11 = new javax.swing.JTextField();
        jtxtE12 = new javax.swing.JTextField();
        jtxtE13 = new javax.swing.JTextField();
        jtxtE14 = new javax.swing.JTextField();
        jtxtE15 = new javax.swing.JTextField();
        jtxtE16 = new javax.swing.JTextField();
        jbtnStart = new javax.swing.JButton();
        jbtnStop = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jbtnClear = new javax.swing.JButton();
        jbtnAbrir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCartoes = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnRem = new javax.swing.JButton();
        txtCartao = new javax.swing.JTextField();
        btnLimparCartoes = new javax.swing.JButton();
        jbtnRealce = new javax.swing.JButton();
        jbtnPassoap = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jtxtTitulo = new javax.swing.JTextField();
        jbtnSalvar = new javax.swing.JButton();
        jbtnAjuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador CS");
        setResizable(false);

        jpn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("E01:");

        jLabel2.setText("E02:");

        jLabel3.setText("E03:");

        jLabel4.setText("E04:");

        jLabel5.setText("E05:");

        jLabel6.setText("E06:");

        jLabel7.setText("E07:");

        jLabel8.setText("E08:");

        jLabel9.setText("E09:");

        jLabel10.setText("E10:");

        jLabel11.setText("E11:");

        jLabel12.setText("E12:");

        jLabel13.setText("E13:");

        jLabel14.setText("E14:");

        jLabel15.setText("E15:");

        jLabel16.setText("E16:");

        jtxtE00.setText("PGC E16");
        jtxtE00.setMaximumSize(new java.awt.Dimension(150, 20));
        jtxtE00.setName("1"); // NOI18N

        jtxtE02.setText("PGC E15");
        jtxtE02.setMaximumSize(new java.awt.Dimension(150, 20));
        jtxtE02.setName("2"); // NOI18N

        jtxtE03.setText("SE E15< E16, E05");
        jtxtE03.setMaximumSize(new java.awt.Dimension(150, 20));
        jtxtE03.setName("3"); // NOI18N

        jtxtE04.setText("VT E02");
        jtxtE04.setMaximumSize(new java.awt.Dimension(150, 20));
        jtxtE04.setName("4"); // NOI18N

        jtxtE05.setText("IMP E16");
        jtxtE05.setMaximumSize(new java.awt.Dimension(150, 20));
        jtxtE05.setName("5"); // NOI18N
        jtxtE05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtE05ActionPerformed(evt);
            }
        });

        jtxtE06.setText("PARE");
        jtxtE06.setMaximumSize(new java.awt.Dimension(150, 20));
        jtxtE06.setName("6"); // NOI18N
        jtxtE06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtE06ActionPerformed(evt);
            }
        });

        jtxtE07.setText("jTextField1");
        jtxtE07.setMaximumSize(new java.awt.Dimension(150, 20));
        jtxtE07.setName("7"); // NOI18N

        jtxtE08.setText("jTextField1");
        jtxtE08.setMaximumSize(new java.awt.Dimension(150, 20));
        jtxtE08.setName("8"); // NOI18N

        jtxtE09.setText("jTextField1");
        jtxtE09.setMaximumSize(new java.awt.Dimension(150, 20));
        jtxtE09.setName("9"); // NOI18N

        jtxtE10.setText("jTextField1");
        jtxtE10.setMaximumSize(new java.awt.Dimension(150, 20));
        jtxtE10.setName("10"); // NOI18N

        jtxtE11.setText("jTextField1");
        jtxtE11.setMaximumSize(new java.awt.Dimension(150, 20));
        jtxtE11.setName("11"); // NOI18N

        jtxtE12.setText("jTextField1");
        jtxtE12.setMaximumSize(new java.awt.Dimension(150, 20));
        jtxtE12.setName("12"); // NOI18N

        jtxtE13.setText("jTextField1");
        jtxtE13.setMaximumSize(new java.awt.Dimension(150, 20));
        jtxtE13.setName("13"); // NOI18N

        jtxtE14.setText("jTextField1");
        jtxtE14.setMaximumSize(new java.awt.Dimension(150, 20));
        jtxtE14.setName("14"); // NOI18N

        jtxtE15.setText("jTextField1");
        jtxtE15.setMaximumSize(new java.awt.Dimension(150, 20));
        jtxtE15.setName("15"); // NOI18N

        jtxtE16.setText("jTextField1");
        jtxtE16.setMaximumSize(new java.awt.Dimension(150, 20));
        jtxtE16.setName("16"); // NOI18N

        javax.swing.GroupLayout jpn1Layout = new javax.swing.GroupLayout(jpn1);
        jpn1.setLayout(jpn1Layout);
        jpn1Layout.setHorizontalGroup(
            jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtE00, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtE02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtE03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtE04, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtE05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtE08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addGroup(jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtE07, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtE06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtE09, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtE16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtE15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtE14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtE13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtE12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtE11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtE10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpn1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtE09, jtxtE10, jtxtE11, jtxtE12, jtxtE13, jtxtE14, jtxtE15, jtxtE16});

        jpn1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtE00, jtxtE02, jtxtE03, jtxtE05, jtxtE07, jtxtE08});

        jpn1Layout.setVerticalGroup(
            jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtE00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtE09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(jtxtE02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtE10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11)
                    .addComponent(jtxtE03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtE11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(jtxtE04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtE12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13)
                    .addComponent(jtxtE05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtE13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14)
                    .addComponent(jtxtE14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtE06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15)
                    .addComponent(jtxtE07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtE15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel16)
                    .addComponent(jtxtE08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtE16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jbtnStart.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnStart.setText("INICIAR");
        jbtnStart.setToolTipText("Iniciar simulação");
        jbtnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStartActionPerformed(evt);
            }
        });

        jbtnStop.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnStop.setText("PARAR");
        jbtnStop.setToolTipText("Encerrar simulação");
        jbtnStop.setEnabled(false);
        jbtnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStopActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Programa / Valores Iniciais do Escaninho");
        jLabel18.setMaximumSize(new java.awt.Dimension(50, 14));
        jLabel18.setMinimumSize(new java.awt.Dimension(40, 14));
        jLabel18.setPreferredSize(new java.awt.Dimension(45, 14));

        jbtnClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnClear.setText("LIMPAR");
        jbtnClear.setToolTipText("Limpar todos os campos");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        jbtnAbrir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnAbrir.setText("ABRIR");
        jbtnAbrir.setToolTipText("Abrir projeto");
        jbtnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAbrirActionPerformed(evt);
            }
        });

        tblCartoes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblCartoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cartões"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCartoes.setToolTipText("");
        tblCartoes.setAutoscrolls(false);
        tblCartoes.setFocusable(false);
        tblCartoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCartoesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCartoes);

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdd.setToolTipText("Adicionar cartão");
        btnAdd.setLabel("+");
        btnAdd.setPreferredSize(new java.awt.Dimension(40, 23));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRem.setToolTipText("Remover cartão");
        btnRem.setEnabled(false);
        btnRem.setLabel("-");
        btnRem.setPreferredSize(new java.awt.Dimension(40, 23));
        btnRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemActionPerformed(evt);
            }
        });

        txtCartao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCartaoKeyPressed(evt);
            }
        });

        btnLimparCartoes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLimparCartoes.setText("Limpar");
        btnLimparCartoes.setToolTipText("Remover todos os cartões");
        btnLimparCartoes.setEnabled(false);
        btnLimparCartoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCartoesActionPerformed(evt);
            }
        });

        jbtnRealce.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnRealce.setText("REALCE");
        jbtnRealce.setToolTipText("Iniciar simulação com realce");
        jbtnRealce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRealceActionPerformed(evt);
            }
        });

        jbtnPassoap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnPassoap.setText("P a P");
        jbtnPassoap.setToolTipText("Iniciar simulação passo a passo");
        jbtnPassoap.setEnabled(false);
        jbtnPassoap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPassoapActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Título: ");

        jtxtTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtTitulo.setText("teste");
        jtxtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTituloActionPerformed(evt);
            }
        });

        jbtnSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnSalvar.setText("SALVAR");
        jbtnSalvar.setToolTipText("Salvar projeto");
        jbtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalvarActionPerformed(evt);
            }
        });

        jbtnAjuda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnAjuda.setText("AJUDA");
        jbtnAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAjudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCartao, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLimparCartoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnAbrir)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnRealce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnPassoap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnAjuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnClear, jbtnStart, jbtnStop});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimparCartoes))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnSalvar)
                            .addComponent(jLabel17)
                            .addComponent(jtxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnAbrir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnStart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnRealce)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnPassoap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnStop)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnClear)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnAjuda))
                            .addComponent(jpn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStartActionPerformed
        // TODO add your handling code here:

        jbtnStart.setEnabled(false);
        jbtnStop.setEnabled(true);
        jbtnClear.setEnabled(false);
        jbtnPassoap.setEnabled(false);
        jbtnRealce.setEnabled(false);
        jbtnAbrir.setEnabled(false);
        jbtnSalvar.setEnabled(false);

        txtCartao.setEnabled(false);
        jtxtTitulo.setEnabled(false);
        btnAdd.setEnabled(false);
        btnLimparCartoes.setEnabled(false);
        runCS.start();
    }//GEN-LAST:event_jbtnStartActionPerformed

    private void jbtnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStopActionPerformed
        // TODO add your handling code here:
        runCS.stop();
        rrunCS.stop();
        jbtnStart.setEnabled(true);
        jbtnStop.setEnabled(false);
        jbtnClear.setEnabled(true);
        jbtnRealce.setEnabled(true);
        jbtnAbrir.setEnabled(true);
        jbtnSalvar.setEnabled(true);

        txtCartao.setEnabled(true);
        jtxtTitulo.setEnabled(true);
        btnAdd.setEnabled(true);
        if (!getCards().isEmpty()) {
            btnLimparCartoes.setEnabled(true);
        }
    }//GEN-LAST:event_jbtnStopActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        // TODO add your handling code here:
        clearJTextFields(1);
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAbrirActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter txtType = new FileNameExtensionFilter("TEXT FILES", "txt");
        fc.setFileFilter(txtType);
        fc.addChoosableFileFilter(txtType);
        fc.setAcceptAllFileFilterUsed(false);
        int k = fc.showOpenDialog(this);

        if (k == JFileChooser.APPROVE_OPTION) {
            arquivoCS = new ArquivoCS(this);
            try {
                List<String> conteudo = arquivoCS.abrir(fc.getSelectedFile().toString());
                jtxtTitulo.setText(fc.getSelectedFile().getName().substring(0, fc.getSelectedFile().getName().indexOf(".")));
                clearJTextFields(1);
                int size = conteudo.size();
                while (conteudo.size() > 0) {
                    String linha = conteudo.remove(0);
                    String[] data = linha.split(":");
                    for (int i = 1; i <= textMap.size(); i++) {
                        JTextField jtxt = textMap.get(i);
                        String name = jtxt.getName();
                        if (name.equals(data[0])) {
                            if (data[1].equals(" ")) {
                                jtxt.setText("");
                            } else {
                                jtxt.setText(data[1]);
                            }
                            break;
                        }
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERRO AO ABRIR ARQUIVO!");
            }
        }

    }//GEN-LAST:event_jbtnAbrirActionPerformed

    private void jbtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalvarActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setSelectedFile(new File(jtxtTitulo.getText() + ".txt"));
        int i = fc.showSaveDialog(this);

        if (i == JFileChooser.APPROVE_OPTION) {
            String path = new String();
            try {
                if (fc.getSelectedFile().getName().substring(fc.getSelectedFile().getName().indexOf(".")).equals(".txt")) {
                    path = fc.getSelectedFile().toString();
                }
            } catch (Exception e) {
                path = fc.getSelectedFile().toString() + ".txt";
            }
            File selFile = new File(path);
            jtxtTitulo.setText(selFile.getName().substring(0, selFile.getName().indexOf(".")));
            try {
                arquivoCS = new ArquivoCS(this);
                arquivoCS.escrever(selFile.toString());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERRO AO SALVAR ARQUIVO!");
            }
        }
    }//GEN-LAST:event_jbtnSalvarActionPerformed

    private void addCartao(Integer card) {
        if (!txtCartao.getText().equals("")) {
            List<Integer> cardList = getCards();
            try {
                cardList.add(card);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Digite apenas números inteiros!");
            }
            listar(cardList);
            txtCartao.setText(null);
            btnLimparCartoes.setEnabled(true);
        }
    }

    private void removeCartao() {
        List<Integer> cardList = getCards();
        cardList.remove(tblCartoes.getSelectedRow());
        listar(cardList);

        btnRem.setEnabled(false);
        if (cardList.isEmpty()) {
            btnLimparCartoes.setEnabled(false);
        }
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (!txtCartao.getText().equals("")) {
            Integer card = Integer.parseInt(txtCartao.getText());
            addCartao(card);
        }
        txtCartao.requestFocus();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnLimparCartoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCartoesActionPerformed
        // TODO add your handling code here:
        List<Integer> emptyList = new ArrayList<>();
        emptyList.clear();
        listar(emptyList);
        btnLimparCartoes.setEnabled(false);
        btnRem.setEnabled(false);
    }//GEN-LAST:event_btnLimparCartoesActionPerformed

    private void jtxtE05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtE05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtE05ActionPerformed

    private void jtxtE06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtE06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtE06ActionPerformed

    private void tblCartoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCartoesMouseClicked
        // TODO add your handling code here:
        btnRem.setEnabled(true);
    }//GEN-LAST:event_tblCartoesMouseClicked

    private void btnRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemActionPerformed
        // TODO add your handling code here:
        removeCartao();
        txtCartao.requestFocus();
    }//GEN-LAST:event_btnRemActionPerformed

    private void jbtnRealceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRealceActionPerformed
        // TODO add your handling code here:
        rrunCS.start();
        jbtnStart.setEnabled(false);
        jbtnStop.setEnabled(true);
        jbtnClear.setEnabled(false);
        jbtnPassoap.setEnabled(false);
        jbtnRealce.setEnabled(false);
        jbtnAbrir.setEnabled(false);
        jbtnSalvar.setEnabled(false);

        txtCartao.setEnabled(false);
        jtxtTitulo.setEnabled(false);
        btnAdd.setEnabled(false);
        btnLimparCartoes.setEnabled(false);
    }//GEN-LAST:event_jbtnRealceActionPerformed

    private void jbtnPassoapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPassoapActionPerformed
        // TODO add your handling code here:
        //paprunCS.start();
        jbtnStart.setEnabled(false);
        jbtnStop.setEnabled(true);
        jbtnClear.setEnabled(false);
        jbtnPassoap.setEnabled(false);
        jbtnRealce.setEnabled(false);

        txtCartao.setEnabled(false);
        btnAdd.setEnabled(false);
        btnLimparCartoes.setEnabled(false);
    }//GEN-LAST:event_jbtnPassoapActionPerformed

    private void jtxtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTituloActionPerformed

    private void txtCartaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCartaoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txtCartao.getText().equals("")) {
                Integer card = Integer.parseInt(txtCartao.getText());
                addCartao(card);
                txtCartao.requestFocus();
            } else if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
                removeCartao();
            }
        }
    }//GEN-LAST:event_txtCartaoKeyPressed

    private void jbtnAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAjudaActionPerformed
        // TODO add your handling code here:
        JdlgComandos comandos = new JdlgComandos(new javax.swing.JFrame(), true);
        comandos.setVisible(true);
    }//GEN-LAST:event_jbtnAjudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JfrmPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnLimparCartoes;
    private javax.swing.JButton btnRem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnAbrir;
    private javax.swing.JButton jbtnAjuda;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnPassoap;
    private javax.swing.JButton jbtnRealce;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JButton jbtnStart;
    private javax.swing.JButton jbtnStop;
    private javax.swing.JPanel jpn1;
    private javax.swing.JTextField jtxtE00;
    private javax.swing.JTextField jtxtE02;
    private javax.swing.JTextField jtxtE03;
    private javax.swing.JTextField jtxtE04;
    private javax.swing.JTextField jtxtE05;
    private javax.swing.JTextField jtxtE06;
    private javax.swing.JTextField jtxtE07;
    private javax.swing.JTextField jtxtE08;
    private javax.swing.JTextField jtxtE09;
    private javax.swing.JTextField jtxtE10;
    private javax.swing.JTextField jtxtE11;
    private javax.swing.JTextField jtxtE12;
    private javax.swing.JTextField jtxtE13;
    private javax.swing.JTextField jtxtE14;
    private javax.swing.JTextField jtxtE15;
    private javax.swing.JTextField jtxtE16;
    private javax.swing.JTextField jtxtTitulo;
    private javax.swing.JTable tblCartoes;
    private javax.swing.JTextField txtCartao;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the textFields
     */
    public List<JTextField> getTextFields() {
        return textFields;
    }
}
